### ISSUE TITLE
Solve axios error shown in console

### ISSUE THREAD

**Issue by borjar20** [governify/commons#8]

**Comment by borjar20** [comment]
This issues depend on an update in the assets #[If post in asset to not existing directory accept param to create i](https://github.com/governify/assets-manager/issues/21)

**Comment by alesancor1** [comment]
Some promises are not correctly handled, in order to solve this issue it is needed to:

- [ ] Update governify-commons to catch the exception produced by PATCH request to assetsmanager when commons.log is not found. This handling will cause assetsmanager to automatically create the file if needed, see comment above.
- [ ] Find and handle the exceptions in any other services where the error produces, since some calls are missing `.catch` in promises, specially those which request directly from `getService()` function.
